### PR TITLE
A quite big pack of changes.

### PR DESCRIPTION
**Pull request by Azoraqua**
* Added LJWGL library selection by detection of OS.
* Fixed causes for a compilation error.
* Optimised code for Java 8.
- Removed some unnecessary code. (Such as replacing List parameters with Diamond Brackets)

### CODE REVIEW

**Comment by Azoraqua** [comment]
Thanks to @AndersBillLinden , for noticing about some errors.

**Comment by MrCrayfish** [comment]
Thanks for your work, however the formatting doesn't match the projects formatting. If you could fix that up, I'll gladly merge this.

**Comment by Azoraqua** [comment]
@MrCrayfish Completely no problem, IntelliJ automatically formats it that way. I'll fix it :)

**Comment by AndersBillLinden** [comment]
Does this compile for you? The last commit on Azoraqua/master being https://github.com/MrCrayfish/ModelCreator/pull/106/commits/0af904a2dd26be3f18c53dcd1f243829bee67b60. In ProjectManager.readComponents path is not defined and reader defined twice. The method ignoreTextureLoading is removed from Importer, making ProjectManager break.

**Comment by Azoraqua** [comment]
@AndersBillLinden Well, Yes. It does compile and run.
I tested it before committing.

**Comment by AndersBillLinden** [comment]
It still seems like Icons.java is completely rewritten because of formatting changes so the diff utility will not tell which lines that are really changed in that big pack. I think it would be wise splitting those changes up into smaller PR:s with descriptive titles.

**Comment by MrCrayfish** [comment]
Still having problems with the formatting on this PR. Only thing stopping it right now.

**Pull request closed without merging**
