### PR TITLE
Add JSON modell importer

### PR DESCRIPTION
**Pull request by andre111**
WARNING: DO NOT MERGE

This is not ready yet. But I wanted to show it to you and ask what you think about it.
I used Gson as I didn't understand the Json library you have included.

It's mostly missing the texture import feature as well as some small flags

### CODE REVIEW

**Comment by andre111** [comment]
I don't know how to do texture loading.
For this reason I added a simple safety check when trying to bind a non existant texture

Maybe to user should specifiy a path where to search for them?

**Comment by andre111** [comment]
Ok I added a way to select a base path for the textures and texture loading.

Something seems of with uv coordinates as trying to load the cocoa model is showing wrong coordinates

**Comment by andre111** [comment]
UV handling must definitly be changed.

For example minecraft supports having the start value bigger than the endvalue to flip the texture, or use a smaller area to stretch to texture,...

Also the programm seems to display the textures with uv coordinates different than minecraft, as the same UV coordinates (see cocoa) lead to different results

**Comment by andre111** [comment]
Ok, I've rewritten the UV system.

Might need to add back the option to automatically set uv end coordinates.

PS: Importing and then exporting the brewingstand model works almost. Rotation of one panel is broken for some reason - investigating

**Comment by andre111** [comment]
Ok I fixed it.
Importing the brewingstand then exporting it and reimporting it works without errors.

But now the rotation slider might be a bit small for the range(-360 to 360)

**Comment by andre111** [comment]
Next problem: the cake textures are flipped upsidedown for some reason

**Comment by andre111** [comment]
Hm, that didn't really fix it. Seems like minecraft behaves different with the uv coordinates if the start is bigger than the end.

**Comment by andre111** [comment]
Ok found the problem:

There is something fundametally wrong with the coordinates in this program.
-> The textures face the correct way, but the model is at the wrong position/rotation.

For example the cocoa_age2 model faces north in the program but should actually face south!

**Comment by andre111** [comment]
I'm not able to figure out how to fix it. But the Z coordinate is definitelly wrong. 
For another example here: The textures are actually correct. But the two "potion holders" on the left side are flipped! (The difference in the texture is a little bit difficult to spot)
example

**Comment by andre111** [comment]
The model importer is basically ready for merge now.
But the Z coordinate being wrong is a huge problem.

**Comment by andre111** [comment]
Oh sorry, it might be an error on the model importer, as it has wrong uv coordinates.

**Comment by andre111** [comment]
Ok, I fixed exporting, but rendering is still wrong.

**Comment by andre111** [comment]
Ok I fixed rendering using a bit of a hacky solution.
You might want to do it in a correct way, but I just can't handle to coordinates of the faces correctly.

Tripwirehook string still gets rendered to low. But that is a completely different issue which has to do with the rescale option of rotation

**Comment by andre111** [comment]
NOW it should really be ready for merge and support every model that minecraft does.

Thing I might consider adding:
Minecraft supports (and often uses) parent models only with different textures or small changes. As this programm is not made for handling parent models, the best I could probably do is read the parent models and combine them into one model when importing.
But that will defenitely have to wait until tomorrow. :P

**Comment by MrCrayfish** [comment]
Man, that was like an adventure reading that. It could almost be a movie haha. Thank you so much and has saved time of my own. Merging now...

**Comment by MrCrayfish** [comment]
In regards to the z coordinates, it was for ease of use. When the as z is incremented, it come closer to you and I did not like that, that's why I made it move away. When exporting though, I would convert the coordinates to work with Minecraft.

**Comment by MrCrayfish** [comment]
In other words, its more user friendly if positive z goes forward rather than coming towards you. I will be make some changes to the importer to respect that fact.

**Comment by andre111** [comment]
But it is really confusing if the coordinates in the programm are not the same as in the inported/exported model

**Comment by MrCrayfish** [comment]
For imported and exported yes, but from scratch it is really nice. North in the creator, is north in the game. If it was reversed, imported would be nice but designing wouldn't so it's win-lose situation.

**Comment by andre111** [comment]
North in the creator should definitely be north in the game, but that is not the problem.

It will be very confusing for everyone who looks at the json and sees different values than in the editor. And I think the moving towards the camera is unimportant compared to that.

**Comment by MrCrayfish** [comment]
I will sort something out. Right now, I do feel like something need to be done but I want to keep the ease of use.

**Comment by andre111** [comment]
The block moving towards the camera doesn't change anything in the ease of use.

But the z coordinate will only confuse and complicate things.

**Comment by MrCrayfish** [comment]
I will try a decide on something. I just purely founder positive z going away to be easier than coming towards you. I will get back to you.

**Comment by MrCrayfish** [comment]
I think I may have thought of an agreeable solution. I will get back to you when I finished coding it.

**Comment by andre111** [comment]
Ok, no problem! You can do whatever you think is the best. I for myself can keep my z changes in my fork for personal use.

**Comment by MrCrayfish** [comment]
Alright. I've decided to go your way, as it's really the only option. Will push a commit soon

**Comment by andre111** [comment]
Also I started a new project.
(I really like this programm and just add what I think could be helpfull for me or others)
That a look a my display_rewrite branch:
https://github.com/andre111/ModelCreator/tree/display_rewrite

Looks like this:
example
Moving and scaling the block(left or rightclick) works.
It even displays the texture of the Block

Things left to do: 
The display only shows the selected Block because I didn't add any depth ordering.
Moving/Scaling the viewport. It is technically ready for this but not added yet.

**Comment by MrCrayfish** [comment]
Just tested it out, looking good. Reminds me a bit of Cubik. I will do some aesthetics touches once you finish it :P

**Comment by andre111** [comment]
Ok added scaling.
It's my first time working with lwjgl/opengl to render things and I'm happy that it even works.

I won't change it only displaying the currently selected block.
It also ignores rotation, but I think it's better this way.

Not sure what to do about the scaling in different directions.

**Comment by MrCrayfish** [comment]
I've really like where you are going, I hate to stop you but this has given more a more unique idea to build upon this concept. Instead other new sidebar, determine the rotation of the camera, when Ctrl+Click and Drag are performed, resize the cuboid faces (which adjusts the whole cuboid). I personally don't want the program to feel like Cubik, but rather an unique model creator compared to the rest. Hopefully you understand my idea. You could keep it in your personal copy though. I might actually do this idea myself

**Comment by andre111** [comment]
I know. It feels a bit too much like Cubik for a release.
This is way I created a sepperate branch for it so I can still make small pull requests with my main branch.

But I really wanted something easier than the buttons.
Scaleing and moving the blocks with the buttons is just taking to long.

As I already (kind of) said I don't really have experience working in 3D space. (Which is why I could figure out how to change the z coordinate correctly without moving the whole space.)
So creating something that works similar to this but in the 3d perspective is over my capabilities.

**Comment by MrCrayfish** [comment]
The z fix was easy, all you had to do was remove the negative z from the quad rendering. Any chance you have skype?

**Comment by MrCrayfish** [comment]
I've fixed the UV's in a new commit. I also added my new control scheme for designing. Tip: Hold Ctrl and use left or right click ;)

**Comment by andre111** [comment]
I like it, but it is not as easy/quick to use as the grid/sidebar.

I also made a few new commits to my display_rewrite branch. Just select the faces tab and set a texture and you will see. :)

**Comment by MrCrayfish** [comment]
I swapped them over for something else but scrapped the idea and forgot to change it back. WIll get onto reverting that. Also I will update the copy issue too.

**Comment by andre111** [comment]
What do you think about my other additions?

**Comment by MrCrayfish** [comment]
Gonna check it out in a minute :hankey:

**Comment by MrCrayfish** [comment]
Oh very nice. A UV mapper. I think that'll definitely be added into the main program.

**Comment by andre111** [comment]
Also your new system for moving elements doesn't work if you turn the camera upside down and the right side up again (performing 360°).

**Comment by MrCrayfish** [comment]
Yeah, I've still got to finish off some code. Really just got it out there for you to see my concept I had in mind.

**Comment by andre111** [comment]
My display_rewrite branch now supports loading parent models and I fixed a texture loading bug in the prozess.
It also includes all of your changes.(UV fix, menu reorder but nor that switched faces)

**Comment by andre111** [comment]
Noticed something wiered.
Try importing piston_head_normal.json in my latest build.
Some UV coordinates are not right. They load the correct values but display wrong pixels.
It seems like minecraft rotates not only the texture but also the UV coordinates?

**Comment by andre111** [comment]
You didn't respond but because this is a serious issue I'm commenting again so you wil hopefully see it.

Rotated textures are not displayed correctly in the programm. This also means when you create a face with a rotated texture in the programm it will be wrong in minecraft.
You should fix it before you release a new version. I cann't fix it as I don't completely understand what is wrong with it.

**Comment by MrCrayfish** [comment]
Sorry for not getting back, I've been busy University work. I will get onto the issue soon :)

**Comment by andre111** [comment]
Made another interesting little change to my display_rewrite branch. You might want to check it out. ;)

**Comment by MrCrayfish** [comment]
Yes sir!

**Comment by andre111** [comment]
What do you think about it?

**Comment by MrCrayfish** [comment]
I don't know what to do. I see that there is a selection method. I shift and click, but I dont know where XD

**Comment by MrCrayfish** [comment]
Seems like I can't select with Shift click

**Comment by andre111** [comment]
That was just a test. Try ctrl clicking/dragging on any element.

**Comment by andre111** [comment]
Also I went a bit crazy and extended the selection system just a tiny bit.

This was the result:
https://github.com/andre111/ModelCreator/tree/display_rewrite_new
Try creating a full block and the shift leftclicking on it like mad. :P 

I will probably not develop it any further. (Doesn't have texture and UV support)
Maintaining this code would be hell.

**Comment by MrCrayfish** [comment]
You have gone absolutely insane XD

**Comment by andre111** [comment]
I was bored. So I continued working on it anyway.
Added some basic UV support:
example

**Comment by MrCrayfish** [comment]
I've been working on my version of the sidebar. I think you'll like it. I still need to add input to handle adjusting the uv. Screenshot

**Comment by andre111** [comment]
Still working on supporting rotated textures in my pixel deletion code.

Got distracted by your screenshot. My sidebar now also looks like this:
example2

**Comment by MrCrayfish** [comment]
Ignore the order of the colours right now. I had not ordered them correctly.

**Comment by andre111** [comment]
Just made another cool addition to my display_rewrite_new branch.
It now supports loading animated textures using the mcmeta file

It's not quiet finished yet. It misses support for interpolate and the first time each frame is displayed the animation looks a bit buggy.

**Comment by MrCrayfish** [comment]
Finished the main part of my sidebar UV editor. Hint: Make the window height smaller ;P

**Comment by andre111** [comment]
Ok that is really nice.
You have one small error though:
example
I wont implement that because mine are zoomable and I think they still have an acceptable size when the window is at its smallest size.

What do you think about my implementation of animated textures?

**Comment by MrCrayfish** [comment]
Yeah I like the idea. The more features to make it support every possible rendering option, the better

**Comment by MrCrayfish** [comment]
Also I'm gonna fix the rotation on the uv sidebar problem by not rotating the texture.

**Comment by andre111** [comment]
Textures now support even the blur and interpolate(prismarine) options

**Pull request merged**
