### PR TITLE
mcmeta support for textures

### PR DESCRIPTION
**Pull request by andre111**
This pull request adds mcmeta support for textures.

Implemented:
Animated Textures
Interpolation
Blur

Not Implemented:
~~Custom Frametime per frame~~
clamp

I'm not sure if I ported everything correctly, but in my tests everything worked correctly.

edit: Custom frametime should be working now(not tested)

### CODE REVIEW

**Comment by andre111** [comment]
I have two other small pull requests ready which I will make once this one is merged.

**Comment by MrCrayfish** [comment]
Will merge tonight as I don't have access to a computer with internet at the moment. I will be doing some refactoring to the code as well.

**Comment by andre111** [comment]
I'm sorry, but I'm not very experienced with git and I have no idea how to fix conflicts

**Comment by MrCrayfish** [comment]
I will manually add you code in or you can resubmit the commit. Sorry about updating the code, I had it sitting on my laptop for a couple of days and forgot to commit it.

**Comment by MrCrayfish** [comment]
I've added in the code to the master branch. Thank you!

**Pull request closed without merging**
