### PR TITLE
Added .java file extension.

### PR DESCRIPTION
**Pull request by Azoraqua**
Stupid fault of mine, I forgot.

### CODE REVIEW

**Comment by AndersBillLinden** [comment]
This fails to compile, even with the extension.

**Comment by AndersBillLinden** [comment]
In `importer.java`, there is code before the try block starts. In `ResourceUtil.java`, there are two overloaded methods with the same parameter type, only differing by return type, which is not supported (http://stackoverflow.com/questions/2439782/overload-with-different-return-type-in-java).

**Comment by Azoraqua** [comment]
Let's fix :)

**Comment by AndersBillLinden** [comment]
It seems you can close this pull request because of https://github.com/MrCrayfish/ModelCreator/pull/102.

**Pull request closed without merging**
